
workflows:
  flutter-clean-build:
    name: Clean Flutter Build for APK
    max_build_duration: 10
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Clean previous builds
        script: flutter clean
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
